### ISSUE TITLE
Embedded survey functionality

### ISSUE THREAD

**Issue by mmertsock** [CareEvolution/MyDataHelpsKit-iOS#2]
Add the ability to open a survey in web view controller within the containing app. Make sure to include functioning demo code in the example app.

See https://github.com/CareEvolution/MyDataHelps.js/pull/18

**Comment by mmertsock** [comment]
@chrisnowak I have this fully functional, including notifying the caller upon survey completion so the window can be closed, etc. But I had to do a bit of a hack to get the survey completion callback to work: embedding the survey in an iframe within the native webview; so that `$scope.embedded == true`, triggering [`window.parent.postMessage({ name: "SurveyFinished" ... })`](https://github.com/CareEvolution/Consumers/blob/a3444fc3609aebcf423641c5ad81598d617af6bd/Mogul/Code/ResearchKit/Scripts/ResearchKit/MyDataHelpsAnonymous.js#L23-L29), which the iframe forwards to the actual WKWebView.

I would propose making some changes to MyDataHelpsAnonymous.js to better support embedded surveys in the Android/iOS SDK. If it can just check for the existence of `window.webkit.messageHandlers.SurveyFinished`, that would be simplest. Or if necessary it could check for an `emdedded=true` URL param (we're already using a URL param to specify the language for localization, so this seems reasonable to me).

**Comment by chrisnowak** [comment]
Yes this is precisely what I was thinking...would not embed in an iframe but would update MyDataHelpsAnonymous.js to better support the SDK use case and to specifically call back via messageHandlers

**Comment by mmertsock** [comment]
Created https://github.com/CareEvolution/Consumers/issues/9768 for the change to MyDataHelpsAnonymous.js
