### ISSUE TITLE
Strongly typed identifiers

### ISSUE THREAD

**Issue by mmertsock** [CareEvolution/MyDataHelpsKit-iOS#28]
Introduce some semi-opaque data types for various identifiers such as participantID, projectID, etc., as an alternative to just using bare String values everywhere. This would prevent SDK clients from accidentally using the wrong type of identifier, causing runtime problems such as unexpectedly empty/error responses.

This would be a **breaking change**, schedule for v2.0.0.

**Comment by lynnfaraday** [comment]
We'll need to put some infrastructure changes in place to support multiple versions of the SDK within the docs.  It's not a huge deal; we already have a pattern in FHIR so I know what to do.  We just need to coordinate in advance of it being published.

**Comment by mmertsock** [comment]
Is there significant value in maintaining documentation on the web for previous SDK versions?

At least for the iOS SDK docs, the inline documentation comments are always available with any version of the SDK, will appear in Xcode's help panels, etc., since they are embedded in the code.

**Comment by mmertsock** [comment]
Sounds good. I don't have a compelling counter-argument 🙂
