### ISSUE TITLE
Investigate structured concurrency support

### ISSUE THREAD

**Issue by mmertsock** [CareEvolution/MyDataHelpsKit-iOS#36]
MyDataHelpsKit has lots of asynchronous code that would be a natural fit for Swift async/await, actors, etc. Look into how best to support this, given the iOS 13 minimum requirement for Swift concurrency.

**Comment by mmertsock** [comment]
Proposed implementation:

- Update SDK to require iOS 13.
- For each API method (basically, each function in [ParticipantSession](https://github.com/CareEvolution/MyDataHelpsKit-iOS/blob/main/MyDataHelpsKit/Session/ParticipantSession.swift)), implement both an async version and a legacy completion-callback function.
- Mark `ParticipantSession` as `@MainActor`.

Example:

```swift
// SDK
@MainActor final class ParticipantSession {
    public func getParticipantInfo() async throws -> ParticipantInfo { }
    public nonisolated func getParticipantInfo(completion: @escaping (Result<ParticipantInfo, MyDataHelpsError>) -> Void) { }
}

// Usage in SwiftUI
@MainActor class SomeSwiftUIViewModel: ObservableObject {
    @Published var name: String?
    func fetchInfo() async {
        do {
            let info = try await session.getParticipantInfo()
            name = info.demographics.firstName
        } catch {
            print(error)
        }
    }
}

// Usage in UIKit
class MyViewController {
    @IBOutlet var nameLabel: UILabel!
    func fetchInfo() {
        Task {
            do {
                let info = try await session.getParticipantInfo()
                // async continuation guaranteed to be on main thread.
                nameLabel.text = info.demographics.firstName
            } catch {
                print(error)
            }
        }
    }
}
```

The `@MainActor` annotation guarantees that the caller of ParticipantSession's async functions will always continue on the main thread, with no effort required either in the caller or within the body of each individual ParticipantSession async function. The underlying network communication and response parsing would run asynchroniously on the URLSession's background thread.

Thinking that 95% of usages of these APIs will be to update the UI immediately after receiving an API response, and it would be rare for any handling of the response data to be computationally heavy; in exceptional circumstances the caller could dispatch such work to a background thread after getting the response. But in the typical case of updating a UIKit view or SwiftUI view model upon receiving the response, no extra code would be necessary to perform that update on the main thread.

If desired we could actually mark the initializer of ParticipantSession as `nonisolated`, so that creating the ParticipantSession instance can happen on any thread (ParticipantSession's internal member properties are immutable and inherently thread-safe).

Other designs considered and rejected:

- Creating a separate `@MainActor` class as a counterpart to ParticipantSession for all async methods, and leaving the completion-callback versions in the existing ParticipantSession. This seems unnecessary, and could complicate a client app that wants to use a mix of async and non-async methods. Apple's frameworks that are adopting structured concurrency (e.g. HealthKit, URLSession, etc.) follow the proposed pattern above, of adding async overloads within the same existing class.
- Leaving out the `@MainActor` annotation. This somewhat simplifies the implementation within the SDK, and allows the caller to control what thread the async code returns in. This is more flexible but makes it easier for the caller to introduce updating-UI-on-background-thread bugs. I think the pros of MainActor outweigh the cons.

@eschramm — thoughts? Do you support the overall architecture proposed, decisions on where to put the async functions, the usage of MainActor, etc.? See any potential problems?

**Comment by mmertsock** [comment]
Actually, perhaps it's ok commit entirely to structured concurrency, and have ParticipantSession _only_ include async methods, removing the completion-callback functions entirely. It seems easy enough for Swift callers to wrap these async methods in `Task { ... }` for non-async contexts. And Objective-C compatibility, etc., is a non-issue: since v1.0 of the SDK we have required the caller to implement their own Objective-C shims.

**Comment by eschramm** [comment]
While I understand that most calls to ParticipantSession functions for data retrieval would result in some UI updates, what if the developer wants to graph some DeviceDataPoints, doing some further processing. If we've tagged @MainActor on the ParticipantSession actor, wouldn't that by default cause that processing to occur on the main thread unless the developer realizes this and detached the processing part manually? And in my experience, the compiler seems to be doing a good job of calling out when touching UI elements while working in an async context so my gut feeling is it could be overkill?

**Comment by mmertsock** [comment]
I think that's a convincing argument.
