### ISSUE TITLE
APIs for provider accounts

### ISSUE THREAD

**Issue by mmertsock** [CareEvolution/MyDataHelpsKit-iOS#5]
Implement delete provider account and connect external account using delegated APIs.

See https://github.com/CareEvolution/Consumers/issues/9335, https://github.com/CareEvolution/Consumers/pull/9736, and https://github.com/CareEvolution/MyDataHelps.js/pull/17

**Comment by mmertsock** [comment]
The linked issues above describe newer delegated API endpoints for listing/searching/refreshing provider accounts. To actually _create_ a provider connection, are there no new APIs, just the ones currently used by the first-party MyDataHelps apps? Is it even possible to use a delegated access token with the existing APIs to create a new connection?

**Comment by chrisnowak** [comment]
No...that is the rocket science we need to invest in:
https://github.com/CareEvolution/Consumers/issues/9419
