### ISSUE TITLE
Standalone Survey Support

### ISSUE THREAD

**Issue by tanvdo** [CareEvolution/MyDataHelpsKit-iOS#52]
Web support for standalone surveys without using the anonymous link identifiers was added in https://github.com/CareEvolution/MyDataHelps.js/pull/89. The mobile SDKs can/should support this functionality as well.

**Comment by mmertsock** [comment]
We can remove the previous embedded survey implementation from this SDK, right?

**Comment by tanvdo** [comment]
I believe so. @chrisnowak Can you confirm?

**Comment by chrisnowak** [comment]
I don't see a reason to keep it
